/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as AbaixoAssinadosRouteImport } from './routes/abaixo-assinados'
import { Route as IndexRouteImport } from './routes/index'

const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AbaixoAssinadosRoute = AbaixoAssinadosRouteImport.update({
  id: '/abaixo-assinados',
  path: '/abaixo-assinados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abaixo-assinados': typeof AbaixoAssinadosRoute
  '/eventos': typeof EventosRoute
  '/voluntarios': typeof VoluntariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abaixo-assinados': typeof AbaixoAssinadosRoute
  '/eventos': typeof EventosRoute
  '/voluntarios': typeof VoluntariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abaixo-assinados': typeof AbaixoAssinadosRoute
  '/eventos': typeof EventosRoute
  '/voluntarios': typeof VoluntariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abaixo-assinados' | '/eventos' | '/voluntarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abaixo-assinados' | '/eventos' | '/voluntarios'
  id: '__root__' | '/' | '/abaixo-assinados' | '/eventos' | '/voluntarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbaixoAssinadosRoute: typeof AbaixoAssinadosRoute
  EventosRoute: typeof EventosRoute
  VoluntariosRoute: typeof VoluntariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abaixo-assinados': {
      id: '/abaixo-assinados'
      path: '/abaixo-assinados'
      fullPath: '/abaixo-assinados'
      preLoaderRoute: typeof AbaixoAssinadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbaixoAssinadosRoute: AbaixoAssinadosRoute,
  EventosRoute: EventosRoute,
  VoluntariosRoute: VoluntariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
